FORMAT: 1A
HOST: https://api.crowdemotion.co.uk

# New re-designed Developers Documentation

Please, find the new Developers Documentation in the following link:
[http://developers.crowdemotion.co.uk/](http://developers.crowdemotion.co.uk/)
